services:
  micro-news:
    image: micro-news
    environment:
      - MYSQL_HOST=microserviceproject-micro-database-1
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=news-service
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "9040:9040"
    depends_on:
      - micro-eureka
      - micro-database
    networks:
      - micro-network

  micro-eureka:
    image: micro-eureka
    environment:
      - EUREKA_HOST=micro-eureka
      - SERVER_PORT=8099
    ports:
      - "8099:8099"
    networks:
      - micro-network

  micro-database:
    image: db-news
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    ports:
      - "3307:3306"
    networks:
      - micro-network

networks:
  micro-network:
    driver: bridge
