services:
  micro-news:
    image: micro-news
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://microserviceproject-micro-database-1:3306/news-service?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8099/eureka
    ports:
      - 9040:9040
    depends_on:
      - micro-eureka
      - micro-database
    networks:
      - micro-network

  micro-eureka:
    image: micro-eureka
    ports:
      - 8099:8099
    networks:
      - micro-network

  micro-database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    ports:
      - 3307:3306
    networks:
      - micro-network

networks:
  micro-network:
    driver: bridge